FROM ubuntu:22.04

# Install system dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    ssh \
    git \
    curl \
    && apt-get clean

# Upgrade pip and install Ansible + FastAPI dependencies
RUN pip3 install --no-cache-dir --upgrade pip \
    && pip3 install ansible uvicorn fastapi

# Set working directory
WORKDIR /Scripts/API

# Copy requirements and install
COPY ./requirements.txt /project_hosting/Scripts/API/requirements.txt
RUN pip3 install --no-cache-dir --upgrade -r /project_hosting/Scripts/API/requirements.txt

# Copy FastAPI app
COPY ./app /app

# Expose port for FastAPI
EXPOSE 8080

# Run FastAPI app
ENTRYPOINT ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
