version: '3.9'

networks:
  ansible-stack: {}

services:
  app:
    image: fastapi-ansible-image:latest
    build:
      context: /project_hosting/Scripts/API
    container_name: fastapi-ansible
    restart: always
    ports:
      - "8080:8080"
    networks:
      - ansible-stack
